name: Deploy Project
on: [push, workflow_dispatch]
env:
  NAME: "Palash"
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Hello $NAME! Started the workflow"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v4
      - run: node -v
  Results:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Completed last job successfully"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Show all pre-installed sofyware in runner machine
        run: apt list --installed
           
        
        
