name: Deploy Project
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prine Name
        run: echo "Running my workflow"
        run: ls -l
      - name: Print by message
        run: echo "Finished the workflow - Bye!"
