name: First Workflow
on: requst_dispatch
env: NAME="Palash"
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "${NAME} Hello World!"
    - name: Print goodbye
      run: echo "Done - bye!"
