name: Deploy Project
on: [workflow_dispatch]
env:
  NAME: "Palash"
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Hello $NAME! Started the workflow"
        env:
          NAME: "Friend"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
  Results:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: echo "Completed last job successfully"
      - name: Get Code
        uses: actions/checkout@v3
      - name: Show all pre-installed sofyware in runner machine
        run: apt list --installed
           
        
        
