# name: Deploy Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print Name
        run: |
            echo "Running my workflow"
            ls -l
      - name: Print by message
        run: echo "Finished the workflow - Bye!"
